#!/usr/bin/env bash
# Regenerate the throwaway PKI embedded in tests/tls/certs.h. Only needed when
# the certs approach their expiry; requires openssl(1) with EC support.
set -euo pipefail
d=$(mktemp -d)
trap 'rm -rf "$d"' EXIT

openssl ecparam -genkey -name prime256v1 -out "$d/ca.key"
openssl req -x509 -new -key "$d/ca.key" -sha256 -days 3650 \
  -out "$d/ca.crt" -subj "/CN=cornet-test-ca"

openssl ecparam -genkey -name prime256v1 -out "$d/server.key"
openssl req -new -key "$d/server.key" -out "$d/server.csr" -subj "/CN=localhost"
printf "subjectAltName=DNS:localhost,IP:127.0.0.1\nbasicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n" > "$d/server.ext"
openssl x509 -req -in "$d/server.csr" -CA "$d/ca.crt" -CAkey "$d/ca.key" \
  -CAcreateserial -days 3650 -sha256 -extfile "$d/server.ext" -out "$d/server.crt"

openssl ecparam -genkey -name prime256v1 -out "$d/evil.key"
openssl req -x509 -new -key "$d/evil.key" -sha256 -days 3650 \
  -out "$d/evil.crt" -subj "/CN=cornet-evil-ca"

# The EC PARAMETERS preamble confuses nobody (PEM readers skip it), but it also
# serves no purpose in the embedded header, so strip it.
{
  echo '#ifndef CORNET_TESTS_TLS_CERTS_H'
  echo '#define CORNET_TESTS_TLS_CERTS_H'
  echo
  echo '/* regenerated by tests/tls/gen_certs.sh; cert/key pairs below. */'
  echo
  echo '#include <string_view>'
  echo
  echo 'namespace cornet::test::tls {'
  echo
  emit() {
    echo "inline constexpr std::string_view $1 = R\"PEM("
    cat "$2"
    echo ')PEM";'
    echo
  }
  emit kCaCert     "$d/ca.crt"
  emit kServerCert "$d/server.crt"
  emit kServerKey  "$d/server.key"
  emit kEvilCaCert "$d/evil.crt"
  echo '} // namespace cornet::test::tls'
  echo
  echo '#endif // CORNET_TESTS_TLS_CERTS_H'
} > "$(dirname "$0")/certs.h"

echo "wrote $(dirname "$0")/certs.h"
