# cornet.context.uring
[cornet.context.uring]
capacity=1024

# cornet.context.scheduler
[cornet.context.scheduler]
name="TimeSlice"
cpu_budget="10ms"
io_budget="100us"
batch=32

# cornet.logging.stdout
[cornet.logging.stdout]
level="info"
pattern="%^%L%$ [%Y-%m-%d %T %t] %v"

# cornet.logging.files
#[[cornet.logging.files]]
#path="cornet.log"
#level="info"
#pattern="%L [%Y-%m-%d %T] %v"

# cornet.benchmark
[cornet.benchmark]
num_connections=1024
message_size=1024
total_messages=100000
